api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        route_prefix: /api
    mapping:
        paths: ['%kernel.project_dir%/src/Document']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
